language: node_js
before_script:
- npm install -g grunt-cli
deploy:
  skip_cleanup: true
  provider: npm
  email: jononor@gmail.com
  api_key:
    secure: VfZ9/RRpgfXqnPeiXn7DrDH/1+UdeW406ZhxaNORENUkMLGEWUF3vgl0N2+G4cf3c8T98JwkobrnW32p5fG5NuUdZv9ymhBKD/mSPFE7VOY2llXGTLyVnmcj+YNsN81NZmk+1rS3KyVTfN3RqyZcPiBy/6NaWKamlJOMt8wxNDE=
  on:
    tags: true
    repo: flowhub/the-graph
env:
  global:
  - secure: L+J5DJ4NL9pThNmt9L5QMy4YL3gvkUG9cyp7c+0PEaK+EoN8uFGgFIWpgFpTHoS7F9FD913EFjljoeOWWHhl6H3caQg4aYdNw5yqxQAitRmzY1i7NgO/gMo1KaC7tgTGh8/bWCxoYOzWf41o3T068hI6JR1V+IfM05oM97ZwU+o=
  - secure: SmafZtuZT2C+nbg+HnEG1jPKP48uKpD7HkcwE+96qc3lotsH4aKFvAoaK8xvf3cE+Yt+fnSWe5I9IY42wH/FRGTm8n2WsSaP4Yb8tpxlqNm9tVuLF4ohUChhzzX6eg9poikASDsaUQy6EazLDwchjwLVwa8wUCnP4U8660mzJJc=
